[tool]
[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "liquidsnake", email = "bentsoft365@gmail.com"},
]
dependencies = [
    "python-telegram-bot>=20.2",
    "supabase>=1.0.3",
    "schedule>=1.2.0",
    "dotenv>=0.0.5",
]
requires-python = ">=3.9"
license = {text = "MIT"}
